Fix (un)healthy mixed names
dcos/dcos-diagnostics pull request #201
Opened 2020-09-22 15:04 UTC by janisz

PR #47 introduced Healthy and Unhealthy status aliases.
Unfortunately it mismatched the constants.
This PR brings the proper names.

Refs: https://jira.d2iq.com/browse/COPS-6512

2020-09-22 15:09 UTC, pierrebeitz commented on api/pull.go
> +	// if at least one Unit is not Unhealthy, the host should be set Healthy
is that really true or just a change due to search+replace?

2020-09-23 06:53 UTC, pierrebeitz requested changes
1. i'm a bit suspicious about this only hitting us 2 years after the change.
2. in particular i have not understood what the actual fix is, as we only seem to swap a type alias. have we changed everything but one occurrence?
3. what's it about the added `package api` in `properties_linux_test.go`? the purpose of that change is not mentioned in the commit message.
4. we seem to have yet another false change in the comments in `dcos/interfaces.go`:

2020-09-23 10:45 UTC, janisz commented
1. I'm a bit suspicious about this only hitting us 2 years after the change.

I agree but this code was not changed a lot even before so probably that's why nobody noticed mistake

2. in particular i have not understood what the actual fix is, as we only seem to swap a type alias. have we changed everything but one occurrence?



3. what's it about the added `package api` in `properties_linux_test.go`? the purpose of that change is not mentioned in the commit message.

4. we seem to have yet another false change in the comments in `dcos/interfaces.go`:

   `// Healthy indicates Unit is not healthy` :trollface:

2020-09-23 10:53 UTC, pierrebeitz approved these changes
Thanks for explaining and fixing all the things!

![](https://media.giphy.com/media/KxiRwO7tqXCTDVKobo/giphy.gif)

2020-09-23 14:12 UTC, merged